apiVersion: v1
kind: Service
metadata:
  name: todo-app-srv
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 8080
      targetPort: 8080